spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    database: h2
    properties:
      hibernate: org.hibernate.dialect.H2Dialect
      query.in_clause_parameter_padding: true
